In [1]:
from model_funcs import dataset
from model_funcs import train_and_test
from model_funcs import model
import os
from torch.utils.data import DataLoader
import torch
from torch import nn
import matplotlib.pyplot as plt
import numpy as np
from torchvision import models
from torchinfo import summary

from model_funcs.model import ConvolutionalNet

test = dataset.SpectraDataset('test')
loader_test = DataLoader(test, batch_size= 1, pin_memory= True, shuffle=True)


In [17]:
model = models.get_model("mobilenet_v3_small", weights="DEFAULT")

Downloading: "https://download.pytorch.org/models/mobilenet_v3_small-047dcff4.pth" to /home/alexandre/.cache/torch/hub/checkpoints/mobilenet_v3_small-047dcff4.pth
100%|██████████| 9.83M/9.83M [00:01<00:00, 10.1MB/s]


In [19]:
model

MobileNetV3(
  (features): Sequential(
    (0): Conv2dNormActivation(
      (0): Conv2d(3, 16, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
      (1): BatchNorm2d(16, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
      (2): Hardswish()
    )
    (1): InvertedResidual(
      (block): Sequential(
        (0): Conv2dNormActivation(
          (0): Conv2d(16, 16, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), groups=16, bias=False)
          (1): BatchNorm2d(16, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
          (2): ReLU(inplace=True)
        )
        (1): SqueezeExcitation(
          (avgpool): AdaptiveAvgPool2d(output_size=1)
          (fc1): Conv2d(16, 8, kernel_size=(1, 1), stride=(1, 1))
          (fc2): Conv2d(8, 16, kernel_size=(1, 1), stride=(1, 1))
          (activation): ReLU()
          (scale_activation): Hardsigmoid()
        )
        (2): Conv2dNormActivation(
          (0): Conv2d(16, 16, kernel_size=(1, 1), 

In [12]:
model2 = ConvolutionalNet()

In [10]:
pesos = model.state_dict()

In [11]:
pesos

OrderedDict([('adaptador.weight',
              tensor([[[[-0.0089, -0.0544,  0.2355,  0.2052],
                        [ 0.0546, -0.0644, -0.0995, -0.0773],
                        [ 0.1243, -0.1782,  0.0078, -0.0308],
                        [-0.1275,  0.0540,  0.1942, -0.1145]]],
              
              
                      [[[ 0.0861, -0.1608,  0.0969,  0.0948],
                        [ 0.0537, -0.1019, -0.0452, -0.1263],
                        [-0.0312,  0.0166,  0.1385, -0.1571],
                        [ 0.0894,  0.1340, -0.0315,  0.0903]]],
              
              
                      [[[ 0.0705,  0.0832,  0.1788,  0.0388],
                        [ 0.1586, -0.2255, -0.0099, -0.2353],
                        [ 0.0149,  0.0732, -0.0436,  0.0015],
                        [ 0.1833,  0.0453,  0.1285,  0.0284]]]])),
             ('adaptador.bias', tensor([0.0054, 0.2161, 0.0268])),
             ('base_model.features.0.0.weight',
              tensor([[[[ 8.8910e-01, 

In [14]:
model2.load_state_dict(pesos)

<All keys matched successfully>

In [15]:
model2.state_dict()

OrderedDict([('adaptador.weight',
              tensor([[[[-0.0089, -0.0544,  0.2355,  0.2052],
                        [ 0.0546, -0.0644, -0.0995, -0.0773],
                        [ 0.1243, -0.1782,  0.0078, -0.0308],
                        [-0.1275,  0.0540,  0.1942, -0.1145]]],
              
              
                      [[[ 0.0861, -0.1608,  0.0969,  0.0948],
                        [ 0.0537, -0.1019, -0.0452, -0.1263],
                        [-0.0312,  0.0166,  0.1385, -0.1571],
                        [ 0.0894,  0.1340, -0.0315,  0.0903]]],
              
              
                      [[[ 0.0705,  0.0832,  0.1788,  0.0388],
                        [ 0.1586, -0.2255, -0.0099, -0.2353],
                        [ 0.0149,  0.0732, -0.0436,  0.0015],
                        [ 0.1833,  0.0453,  0.1285,  0.0284]]]])),
             ('adaptador.bias', tensor([0.0054, 0.2161, 0.0268])),
             ('base_model.features.0.0.weight',
              tensor([[[[ 8.8910e-01, 

In [4]:
for name, param in model.named_parameters():

    print(f"{name}: {param.requires_grad}")


adaptador.weight: True
adaptador.bias: True
base_model.features.0.0.weight: False
base_model.features.0.1.weight: False
base_model.features.0.1.bias: False
base_model.features.1.block.0.0.weight: False
base_model.features.1.block.0.1.weight: False
base_model.features.1.block.0.1.bias: False
base_model.features.1.block.1.0.weight: False
base_model.features.1.block.1.1.weight: False
base_model.features.1.block.1.1.bias: False
base_model.features.2.block.0.0.weight: False
base_model.features.2.block.0.1.weight: False
base_model.features.2.block.0.1.bias: False
base_model.features.2.block.1.0.weight: False
base_model.features.2.block.1.1.weight: False
base_model.features.2.block.1.1.bias: False
base_model.features.2.block.2.0.weight: False
base_model.features.2.block.2.1.weight: False
base_model.features.2.block.2.1.bias: False
base_model.features.3.block.0.0.weight: False
base_model.features.3.block.0.1.weight: False
base_model.features.3.block.0.1.bias: False
base_model.features.3.block.

In [85]:
for param in model.parameters():
    param.requires_grad = True

for param in model.features.parameters():
    print(param)

Parameter containing:
tensor([[[[-5.2519e-03, -3.2783e-02,  1.0595e-01],
          [-1.2849e-01,  2.1346e-01,  6.1627e-01],
          [-9.4294e-02, -5.8107e-02,  2.8952e-01]],

         [[ 1.2953e-01,  3.6688e-02,  1.8834e-01],
          [-4.7164e-02,  1.3922e-01,  5.0325e-01],
          [ 9.2799e-02,  8.7551e-02,  5.2051e-01]],

         [[-1.7299e-02, -3.8238e-02, -6.1129e-02],
          [-1.7281e-01,  8.6122e-02,  2.0740e-01],
          [-9.2084e-02, -6.3704e-02,  9.8702e-02]]],


        [[[-2.3221e-01,  4.9465e-02,  5.1348e-02],
          [-4.5540e-02,  1.2232e+00, -1.0734e+00],
          [ 3.9858e-02,  1.7052e+00, -1.7577e+00]],

         [[-4.5753e-01,  2.1417e-01, -6.9173e-02],
          [-4.9311e-02,  2.2667e+00, -2.0212e+00],
          [ 1.8742e-01,  2.7476e+00, -2.8510e+00]],

         [[-9.0108e-02,  5.0516e-02,  4.2271e-02],
          [-1.2911e-02,  7.1184e-01, -6.6935e-01],
          [-2.4415e-02,  1.0500e+00, -1.0339e+00]]],


        [[[-1.1341e-03,  7.8697e-02,  6.4097

In [105]:
model

MobileNetV3(
  (features): Sequential(
    (0): Conv2dNormActivation(
      (0): Conv2d(3, 16, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
      (1): BatchNorm2d(16, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
      (2): Hardswish()
    )
    (1): InvertedResidual(
      (block): Sequential(
        (0): Conv2dNormActivation(
          (0): Conv2d(16, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=16, bias=False)
          (1): BatchNorm2d(16, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
          (2): ReLU(inplace=True)
        )
        (1): Conv2dNormActivation(
          (0): Conv2d(16, 16, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(16, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        )
      )
    )
    (2): InvertedResidual(
      (block): Sequential(
        (0): Conv2dNormActivation(
          (0): Conv2d(16, 64, kernel_size=(1, 1), stride=(1, 1), bi

In [48]:
model = torch.load('models/convolutionalnet.pth')

/tmp/ipykernel_5176/774777495.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model = torch.load('models/convolutionalnet.pth')


In [8]:
X , env = test[20]
print(X)
model.eval()
with torch.no_grad():
    pred = model(X.unsqueeze(0))

tensor([[[-109.9990, -109.9995, -109.9987,  ..., -109.9998, -109.9981,
          -109.9981],
         [-109.9991, -109.9996, -109.9989,  ..., -109.9999, -109.9985,
          -109.9984],
         [-109.9995, -109.9998, -109.9994,  ..., -109.9999, -109.9992,
          -109.9992],
         ...,
         [-110.0000, -110.0000, -110.0000,  ..., -110.0000, -110.0000,
          -110.0000],
         [-110.0000, -110.0000, -110.0000,  ..., -110.0000, -110.0000,
          -110.0000],
         [-110.0000, -110.0000, -110.0000,  ..., -110.0000, -110.0000,
          -110.0000]]])


In [9]:
env,pred

(tensor([0.1177], dtype=torch.float64), tensor([[0.4370]]))

In [ ]:
X

tensor([[[-110.0000, -109.9990, -109.9997,  ..., -109.9993, -109.9986,
          -109.9972],
         [-109.9999, -109.9992, -109.9997,  ..., -109.9994, -109.9989,
          -109.9977],
         [-109.9999, -109.9996, -109.9998,  ..., -109.9997, -109.9994,
          -109.9988],
         ...,
         [-110.0000, -110.0000, -110.0000,  ..., -110.0000, -110.0000,
          -110.0000],
         [-110.0000, -110.0000, -110.0000,  ..., -110.0000, -110.0000,
          -110.0000],
         [-110.0000, -110.0000, -110.0000,  ..., -110.0000, -110.0000,
          -110.0000]]])

In [ ]:
env[0] = env[0]/400

In [ ]:
env

tensor([0.0017, 0.1810])